<?php require('template/newheader.phtml') ?>

<h3>Welcome to Page1</h3>


<?php
echo 'INSERT INTO file_uploads(file_name, file_location) VALUES('."\"employeeID\"".', '."\"projectID\"".', '."\"changedStartTime\"".')';
//echo 'INSERT INTO hoursworked (employeeID, projectID, start_time, end_time) VALUES('."\"employeeID\"".', '."\"projectID\"".', '."\"changedStartTime\"".', '."\"changedEndTime\"".')';

?>

<?php require('template/footer.phtml') ?>
