<?php require('template/newheader.phtml') ?>

    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Post ID</th><th>Subject</th><th>Text</th><th>Timestamp</th><th>User ID</th><
            </tr>
            </thead>
            <tbody>
            <?php foreach ($view->postsExtendedDataSet as $postExtendedData) {
                echo '<tr> <td>' . $postExtendedData->getPostID() . '</td> <td>' . $postExtendedData->getSubject() . '</td> <td>' . $postExtendedData->getText() . '</td> <td>' . $postExtendedData->getTimestamp() . '</td> <td>' . $postExtendedData->getUserID() . '</td> </tr>';
            }
            ?>
            </tbody>
        </table>
    </form>

<?php require('template/footer.phtml') ?>