<?php require('template/newheader.phtml') ?>

<h3>Welcome to Projects</h3>

<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
    <div class="container">

        <div class="col-sm-3">
            <label for="projectname"><b>Project Name</b></label>
            <input class="form-control" type="text" name="projectname" required>
            <input class="btn btn-primary" type="submit" name="addproject" value="Add Project">
        </div>








    <div class="col-sm-3">
        <label for="chooseproject"><b>Choose Projects</b></label>
        <select name='projectID' class="form-control" id="chooseproject">
            <?php foreach ($view->projects as $project){
                echo '<option value="' . $project['projectID'].'">' . $project['name'] . '</option>';
            }
            ?>
        </select>

        <input class="btn btn-primary" type="submit" name="addproject" value="Add Project">
    </div>





    </div>
</form>

<?php require('template/footer.phtml') ?>
