<?php require('template/newheader.phtml') ?>



<h3>Welcome to TalkPhones, join the family by signing up</h3>

<html>
<div>
    <form action="register.php" method="post">
        <div class="container">

            <div class="col-sm-3"
                <p>Please fill in the form to be registered</p>
                <hr class="mb-3">

                <label for="firstname"><b>First Name</b></label>
                <input class="form-control" type="text" name="firstname" placeholder="John" required>

                <label for="lastname"><b>Last Name</b></label>
                <input class="form-control" type="text" name="lastname" placeholder="Smith" required>

                <label for="email"><b>Email</b></label>
                <input class="form-control" type="email" name="email" placeholder="name@email.com" required>

                <label for="password"><b>Password</b></label>
                <input class="form-control" type="password" name="password" placeholder="********" required>

                <hr class="mb-3">
                <input class="btn btn-primary" type="submit" name="signup" value="Sign Up">
            </div>



        </div>

    </form>

</div>
</html>

<?php require('template/footer.phtml') ?>
