<?php require('template/newheader.phtml') ?>

<h3>Welcome to Time Page. Use this form to submit your worked hours</h3>

<div action="time.php" method="post">
    <div class="container">

        <div class="col-sm-3"
        <p>Please fill in the form</p>
        <hr class="mb-3">

        <label for="employeeID"><b>Employee ID</b></label>
        <input class="form-control" type="text" name="employeeID" placeholder="5346" required>

        <label for="firstname"><b>First Name</b></label>
        <input class="form-control" type="text" name="firstname" placeholder="John" required>

        <label for="lastname"><b>Last Name</b></label>
        <input class="form-control" type="text" name="lastname" placeholder="Smith" required>

        <label for="projectName"><b>Project Name</b></label>
        <input class="form-control" type="text" name="projectName" placeholder="Project" required>

        <label for="starttime"><b>Start Time</b></label>
        <input class="form-control" type="datetime-local" name="starttime" placeholder="2019-10-02 18:41:17" >

        <label for="endtime"><b>End Time</b></label>
        <input class="form-control" type="datetime-local" name="endtime" placeholder="2019-10-02 18:41:17" >

        <hr class="mb-3">
        <input class="btn btn-primary" type="submit" name="inserttime" value="Submit">
    </div>

    <div class="filesubmission"
        <form action="upload.php" method="post" enctype="multipart/form-data" pull-right>
            Select a file to upload:
            <input type="file" name="fileToUpload" id="fileToUpload">
    </div>

</form>


<!--
    Project Name
    Start Time
    End Time
-->


<?php require('template/footer.phtml') ?>
