<?php require('template/newheader.phtml') ?>

<h3>Welcome to Time Page. Use this form to submit your worked hours</h3>

<form action="time.php" method="post">
    <div class="container">

        <div class="col-sm-3"
        <p>Please fill in the form</p>
        <hr class="mb-3">

        <label for="employeeID"><b>Employee ID</b></label>
        <input class="form-control" type="text" name="employeeID" placeholder="5346" >

        <label for="firstname"><b>First Name</b></label>
        <input class="form-control" type="text" name="firstname" placeholder="John" >

        <label for="lastname"><b>Last Name</b></label>
        <input class="form-control" type="text" name="lastname" placeholder="Smith" >

        <label for="projectName"><b>Project Name</b></label>
        <input class="form-control" type="text" name="projectName" placeholder="Project" >

        <label for="starttime"><b>Start Time</b></label>
        <input class="form-control" type="datetime-local" name="starttime" placeholder="2019-10-02 18:41:17" >

        <label for="endtime"><b>End Time</b></label>
        <input class="form-control" type="datetime-local" name="endtime" placeholder="2019-10-02 18:41:17" >

        <hr class="mb-3">
        <input class="btn btn-primary" type="submit" name="inserttime" value="Submit">
    </div>
</form>

<div class="filesubmission">

<form action="upload.php" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="employeeIDFile"><b>Employee ID</b></label>
        <input class="form-control" type="text" name="employeeIDFile" placeholder="5346" >

        <label for="filetitle"><b>File Name</b></label>
        <input class="form-control" type="text" name="filetitle" id="filetitle" placeholder="file.docx"> <br>
    </div>
    <div class="form-check">
        <label for="fileToUpload"><b>Upload the signed timesheet here:</b></label>
        <input class="fileToUpload" type="file" name="fileToUpload" id="fileToUpload">
    </div>
    <hr class="mb-3">
    <input class="btn btn-primary" type="submit" value="Upload File" name="submitfile">
</form>
</div>


<?php require('template/footer.phtml') ?>
